version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn ReservasOnline.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=ReservasOnline.settings
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A ReservasOnline worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A ReservasOnline beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  static_data:
  media_data:

networks:
  default:
    driver: bridge 